stages:
  - build

variables:
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/node-api

default:
  image: docker
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username container-registry-rw --password-stdin

build-frontend:
  stage: build
  script:
    - cd frontend
    - docker pull $FRONTEND_IMAGE:latest || true
    - docker build --cache-from $FRONTEND_IMAGE:latest -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA -t $FRONTEND_IMAGE:latest .
    - docker push $FRONTEND_IMAGE --all-tags

build-backend:
  stage: build
  script:
    - cd node-api
    - docker pull $BACKEND_IMAGE:latest || true
    - docker build --cache-from $BACKEND_IMAGE:latest -t $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA -t $BACKEND_IMAGE:latest .
    - docker push $BACKEND_IMAGE --all-tags