stages:
  - test
  - build
  - e2e
  - deploy

variables:
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/node-api
  SERVER_PROD_IP: 5.196.1.111
  SERVER_PROD_USER: root

.container_registry: &container_registry
  image: docker
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username container-registry-rw --password-stdin

test_frontend:
  image: node:lts-bullseye
  stage: test
  cache:
    key:
      files:
        - 'frontend/package-lock.json'
    paths:
      - frontend/node_modules
      - frontend/.npm
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run lint
    - npm audit

test_backend:
  image: node:lts-bullseye
  stage: test
  cache:
    key:
      files:
        - 'node-api/package-lock.json'
    paths:
      - node-api/node_modules
      - node-api/.npm
  script:
    - cd node-api
    - npm ci --cache .npm --prefer-offline
    - npm run lint
    - npm audit
    - npm run test:ci
  coverage: '/All files[^]]*\|[^]]*\s+([\d\.]+)/'

build-frontend: 
  stage: build
  <<: *container_registry
  script:
    - cd frontend
    - docker pull $FRONTEND_IMAGE:latest || true
    - docker build --cache-from $FRONTEND_IMAGE:latest -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA -t $FRONTEND_IMAGE:latest .
    - docker push $FRONTEND_IMAGE --all-tags

build-backend:
  stage: build
  <<: *container_registry
  script:
    - cd node-api
    - docker pull $BACKEND_IMAGE:latest || true
    - docker build --cache-from $BACKEND_IMAGE:latest -t $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA -t $BACKEND_IMAGE:latest .
    - docker push $BACKEND_IMAGE --all-tags

test_e2e:
  stage: e2e
  <<: *container_registry
  script:
    - docker compose up --exit-code-from cypress --abort-on-container-exit
  after_script:
    - docker compose down -v --remove-orphans
  
deploy:
  stage: deploy
  image: alpine
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH 
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$GITLAB_KEY_PRODUCTION" | base64 -d | ssh-add -
  script:
    - mkdir -p ~/.ssh
    - touch ~/.ssh/known_hosts
    - ssh-keyscan -H $SERVER_PROD_IP >> ~/.ssh/known_hosts
    - scp docker-compose.prod.yml root@$SERVER_PROD_IP:/root/docker-compose.prod.yml
    - ssh root@$SERVER_PROD_IP "
      docker login $CI_REGISTRY -u container-registry-rw -p $CI_REGISTRY_PASSWORD &&
      && docker pull $FRONTEND_IMAGE \
      && docker pull $BACKEND_IMAGE \
      docker compose -f docker-compose.prod.yml up -d --force-recreate
      "
  
  