version: "3.9"
services:
  node-api:
    image: $BACKEND_IMAGE
    environment:
      NODE_ENV: production
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  frontend:
    image: $FRONTEND_IMAGE
    ports:
      - target: 80
        published: 80
    restart: always
