version: "3.9"
services:
  node-api:
    image: registry.gitlab.com/dyma705836/cicd-projet1/node-api
    environment:
      NODE_ENV: production
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  frontend:
    image: registry.gitlab.com/dyma705836/cicd-projet1/frontend
    ports:
      - target: 80
        published: 80
    restart: always
